import React, { useState } from 'react';
import { generateScheduleFromPrompt, GeneratedScheduleItem } from '../services/geminiService';
import { Task, TaskCategory } from '../types';
import { Sparkles, X, Check, Loader2, Clock, Tag, ArrowRight } from 'lucide-react';
import { formatTime12h } from '../utils/dateUtils';

interface AIScheduleModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAddTasks: (tasks: Omit<Task, 'id' | 'userId' | 'createdAt'>[]) => Promise<void>;
}

const PRESET_PROMPTS = [
  'Create a daily schedule for me. I have college from 8 AM to 4 PM and I want 2 hours for studying.',
  'Daily productivity routine for a software engineering student waking at 6:30 AM.',
  'Balanced healthy lifestyle routine: exercise, 8 hours work, home cooking, and 8 hours sleep.',
];

export const AIScheduleModal: React.FC<AIScheduleModalProps> = ({
  isOpen,
  onClose,
  onAddTasks,
}) => {
  const [prompt, setPrompt] = useState(PRESET_PROMPTS[0]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedList, setGeneratedList] = useState<GeneratedScheduleItem[]>([]);

  if (!isOpen) return null;

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const items = await generateScheduleFromPrompt(prompt);
      if (items.length === 0) {
        setError('No routine generated. Please refine your prompt or check API settings.');
      } else {
        setGeneratedList(items);
      }
    } catch (err: any) {
      setError(err.message || 'Gemini schedule generation failed.');
    } finally {
      setLoading(false);
    }
  };

  const toggleSelect = (index: number) => {
    setGeneratedList((prev) =>
      prev.map((item, idx) => (idx === index ? { ...item, selected: !item.selected } : item))
    );
  };

  const handleAddSelected = async () => {
    const selected = generatedList.filter((item) => item.selected !== false);
    if (selected.length === 0) {
      setError('Please select at least one task to add.');
      return;
    }

    setSaving(true);
    setError(null);
    try {
      const tasksToAdd: Omit<Task, 'id' | 'userId' | 'createdAt'>[] = selected.map((s) => ({
        title: s.title,
        time: s.time,
        category: s.category,
        description: s.description || 'Generated by AI Schedule Assistant',
        repeat: 'daily',
      }));

      await onAddTasks(tasksToAdd);
      onClose();
    } catch (err: any) {
      setError(err.message || 'Failed to save generated tasks.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div id="ai-schedule-modal" className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-xs">
      <div className="w-full max-w-2xl bg-white rounded-2xl shadow-2xl border border-slate-100 flex flex-col max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-linear-to-r from-indigo-50/50 to-purple-50/50">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-indigo-600 text-white flex items-center justify-center shadow-xs">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900">AI Schedule Assistant</h2>
              <p className="text-xs text-slate-500">Powered by Gemini 2.5</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4 overflow-y-auto flex-1">
          {error && (
            <div className="p-3 text-xs bg-rose-50 text-rose-700 rounded-xl border border-rose-200">
              {error}
            </div>
          )}

          {/* Prompt input */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Tell Gemini about your day:
            </label>
            <textarea
              id="ai-prompt-input"
              rows={3}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. Create a daily schedule for me. I have college from 8 AM to 4 PM and I want 2 hours for studying."
              className="w-full px-3.5 py-2.5 text-sm bg-slate-50 border border-slate-200 rounded-xl focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 text-slate-900 resize-none"
            />
          </div>

          {/* Quick presets */}
          <div>
            <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider block mb-1.5">
              Suggested prompts:
            </span>
            <div className="flex flex-wrap gap-1.5">
              {PRESET_PROMPTS.map((p, i) => (
                <button
                  key={i}
                  type="button"
                  onClick={() => setPrompt(p)}
                  className="text-xs text-left px-2.5 py-1 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg transition-colors line-clamp-1 cursor-pointer"
                >
                  "{p.slice(0, 48)}..."
                </button>
              ))}
            </div>
          </div>

          {/* Generate button */}
          <button
            id="btn-generate-routine"
            type="button"
            onClick={handleGenerate}
            disabled={loading || !prompt.trim()}
            className="w-full py-2.5 px-4 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold rounded-xl flex items-center justify-center gap-2 shadow-xs transition-colors cursor-pointer disabled:opacity-50"
          >
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Designing your routine with Gemini...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                <span>Generate Schedule</span>
              </>
            )}
          </button>

          {/* Generated List */}
          {generatedList.length > 0 && (
            <div className="mt-4 pt-4 border-t border-slate-100">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-700">
                  Generated Routine ({generatedList.filter((x) => x.selected !== false).length} selected)
                </span>
                <span className="text-xs text-slate-400">Select tasks to import</span>
              </div>

              <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
                {generatedList.map((item, idx) => (
                  <div
                    key={idx}
                    onClick={() => toggleSelect(idx)}
                    className={`flex items-center justify-between p-3 rounded-xl border transition-all cursor-pointer ${
                      item.selected !== false
                        ? 'bg-indigo-50/40 border-indigo-200 text-slate-800'
                        : 'bg-white border-slate-200 opacity-60 text-slate-500'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div
                        className={`w-5 h-5 rounded-md flex items-center justify-center border transition-colors ${
                          item.selected !== false
                            ? 'bg-indigo-600 border-indigo-600 text-white'
                            : 'border-slate-300 bg-white'
                        }`}
                      >
                        {item.selected !== false && <Check className="w-3.5 h-3.5" />}
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-semibold">{item.title}</span>
                          <span className="text-xs font-medium text-slate-500 bg-slate-100 px-2 py-0.5 rounded-md flex items-center gap-1">
                            <Clock className="w-3 h-3 text-slate-400" />
                            {formatTime12h(item.time)}
                          </span>
                          <span className="text-[10px] font-medium text-indigo-700 bg-indigo-50 px-1.5 py-0.5 rounded">
                            {item.category}
                          </span>
                        </div>
                        {item.description && (
                          <p className="text-xs text-slate-400 mt-0.5">{item.description}</p>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        {generatedList.length > 0 && (
          <div className="px-6 py-4 border-t border-slate-100 flex items-center justify-end gap-3 bg-slate-50/50">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-xs font-medium text-slate-600 hover:bg-slate-200/60 rounded-xl transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              id="btn-add-all-to-schedule"
              type="button"
              onClick={handleAddSelected}
              disabled={saving}
              className="px-5 py-2 text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl shadow-xs transition-colors flex items-center gap-2 cursor-pointer disabled:opacity-50"
            >
              <span>{saving ? 'Adding to Firebase...' : 'Add All to My Schedule'}</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
